name: Github Page

on:
  push:
    branches:
      - main

jobs:
  github-page:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        env:
          CI: true
        run: |
          npm pkg delete scripts.prepare
          npm ci

      - name: Run Build
        run: |
          npm run build -ws

      - name: Run build Github Page
        run: |
          npm run github:page

      - name: Deploy GitHub Page 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: dist
          force: false
          clean-exclude: pr-preview/
