name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Token
        id: get_workflow_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        env:
          CI: true
        run: |
          npm pkg delete scripts.prepare
          npm ci

      - name: Run build
        run: |
          npm run build -ws

      - name: Release 📦
        if: success()
        run: npm run release:ci -ws
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
